url: https://dushyantk.github.io
baseurl: /dushyant.info/

# Site settings
title: Dushyant Kumar Kashyap
email: dushyant@dushyant.info
description: "I am a skilled and versatile VFX/Animation Pipeline TD with decade full of experience in the industry. My previous experience as a Compositor and TD enables me to bring an artists perspective to the tools I design. I am self motivated, innovative and adapt quickly to new technologies and working practices and I work well under pressure. I aim to excel in the VFX world and to leverage my multidisciplinary abilities acquired from nearly a decade of experience in the VFX industry. Specialities: Pipeline Tool Development which end-user can relate to, Compositing."


# Team names, titles and social links
people:
- name: Shyal Bearsdley
  pic: 1
  position: Senior Software Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Michael D'Sa
  pic: 2
  position: VFX Producer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Kevin Sallee
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/dushyantkashyap/
  - title: facebook
    url:
  - title: stack-overflow
    url: https://stackexchange.com/users/7072964/dushyant
  - title: twitter 
    url: http://twitter.com/dushyantk
  - title: github
    url: http://github.com/dushyantk

# Postal address (add as many lines as necessary)
address:
  - line: 1265 Burnaby St.
  - line: Vancouver, BC V6E 1P

# Build settings
markdown: kramdown
permalink: pretty
